<?php
/**
 * @file
 * dfmp_page.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function dfmp_page_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'About',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '2cd0e12d-fa6e-4a96-9a76-609601da2597',
  'type' => 'page',
  'language' => 'und',
  'created' => 1427882080,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '1dd53f9f-c0ad-4ce2-af5d-e144330815fd',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h1><strong>Growing a brand through open data and the sharing economy</strong></h1>

<p>In what we believe is a world first, images and video of Canberra just got a whole lot easier to search, publish, share and use.</p>

<p>The library is available for images and video of the Canberra and the Canberra Region; how we live it, how we do business, what we make, our way of life and things that show what it means to live here.</p>

<p>A picture says a thousand words. As Brand Canberra works to support the growth in awareness and celebration of Australia’s capital city both domestically and abroad we have provided an innovative boost. The city now has an open data platform or library for finding and publishing images and video to promote the city and region.</p>

<p>The great thing about this image and video library is that is has been developed by Canberra innovators collaborating across business, research organisations and government. The model of this approach is gaining interest and uptake by governments across Australia and around the world to provide similar open data services.</p>

<h2><strong>Why a library?</strong></h2>

<h3>The digital storage dilemma</h3>

<p>How many of us in work and at home have hard drives, memory sticks, CDs and DVDs stored in cupboards, drawers and on desks. All disconnected, separated and not readily available. With the growth in digital data like images and videos, there is a global need to find more integrated, archival and accessible means to share valuable assets and resources.</p>

<h3>Whole of government efficiencies</h3>

<p>The ACT Government has long recognised the need for an ongoing integrated solution to data storage, acquisition, procurement, sharing and finding so as part of the Digital Challenge program a challenge was set to create a whole of government image and video library.</p>

<h3>Brand Canberra growth</h3>

<p>In addition to the internal efficiencies gained form a whole of government platform, images and video are the most valued and shared digital content across digital platforms, web and social media. There are images and videos shared to all manner of platforms every day. We recognised that for the CBR brand to grow we needed to provide a platform to share and trade images for all Canberrans who want to actively collaborate and contribute to promoting and celebrating Canberra and the region.</p>

<p>What began as a need for a whole of government image and video library grew into an exciting and innovative collaboration in turn creating the foundation of a CBR Community Data Platform.</p>

<h2><strong>How did the library happen?</strong></h2>

<p>Through the need for a more integrated whole of government approach to sourcing, storing, sharing and publishing images and in demand for better storage and access options, the requirements were defined and put forth as a Challenge opportunity through the Canberra Digital Challenge program.</p>

<p>The successful winner of that project round was LINK Digital who specialise in CKAN systems for open government data.</p>

<p>Opening data across government and to the public facilitates transparency, ease of sharing data across directorates, public participation and supports innovation by allowing third parties to use the data to develop new digital applications and services.</p>

<blockquote>
<p><em>Imagine being able to easily find an image of Canberra to help promote your city and region. Imagine being able to share or sell images to celebrate what you love, support your local businesses and work collaboratively to grow awareness, pride and recognition of CBR. You’ve just seen the value of the CBR open sourced image and video library. </em></p>
</blockquote>

<h2><strong>Who’s behind the library?</strong></h2>

<p>Brand Canberra along with Data 61 and LINK Digital has developed the data portal for images and videos. This platform gives everyone the opportunity to create and share their own Canberra story.</p>

<h2><strong>What makes this an open source library?</strong></h2>

<p>The exciting potential for the library is that it can connect individuals, business, government and organisations to share, transact and grow a common resource and asset to serve the good of the whole in promoting and celebrating our great city.</p>

<p>Using the power of cloud-based, powerful data management system called CKAN, the ACT Government in collaboration with Canberra business LINK Digital, NICTA and Brand Canberra is providing the platform to streamline publishing, sharing, finding and using data.</p>

<p>Being open source means that the structure of the platform can grow, be improved, adapted and integrated into a host of digital platforms and apps by developers so to future-proof the capability.</p>

<h2><strong>Who is the library for?</strong></h2>

<p>The ACT Government is committed to more transparent and accessible ways of engaging and reporting to the public and this platform is a great example of working with government, business and research organisations to collaborate on innovative outcomes.</p>

<p>The library is an open data platform. It is a place to store, exchange, transact and share images and video of Canberra and the Canberra Region. Initially built for the ACT Government for internal use, the library structure offers the space and potential for community groups, businesses and individuals to use as a shared resource.</p>

<p>Qualifying owners of a collection (data set) create an account that permits them to upload, store, catalogue, sort, retrieve, share and distribute images and video.</p>

<h3>Collection owners</h3>

<p>The owner of a collection (data set) adds their images and video, includes keywords for searching and metadata about their collection and determines the levels of access, viewing, licensing and permissions for other users. For instance, a departmental user may allow only authorised staff within that department to have access, or may make the data set open to all users.</p>

<h3>Collection users</h3>

<p>End users can also create an account and browse and download images and video depending on the licence for each image or video. Any transactions that require permissions or payment are done within the platform.</p>

<h3>Image and video suppliers</h3>

<p>Suppliers of images and video can create an account and add deliver their images to their client’s collection, adding metadata and keywords as specified in their brief. The collection is then managed by the client according to their set level of access and permissions.</p>

<h3>Business users</h3>

<p>Businesses can register to make use of freely available images to promote Canberra and the region and in time they too can also purchase images for sale through the platform, effectively providing a potential future market place to link suppliers of images and videos with suppliers. This potential is similar to a conventional stock library, but the content is specific to Canberra and the region.</p>

<h3>General public, community, sporting groups and organisations</h3>

<p>The public can also register to be a user of images and download images for fair use based on the licence set by the owner. With suitable registration and permission, the platform can also be configured to aggregate social media content around known, specified hashtags. This means the potential to collect social media content around an event, festival or activity can be arranged so the organisers can easily aggregate and share content around their event, or have it featured on the Canberra.com.au website. The platform is primarily used for the #CBR hashtag, but other hashtags can be considered.&nbsp;</p>

<p>Finally the library can provide a platform where groups including individuals, community organisations, sporting clubs, universities and business can store, share and sell images to support the healthy depiction and promotion of the Canberra Region.</p>

<h2><strong>What can the library do?</strong></h2>

<p>The library is built on a powerful open source data portal platform called CKAN. The library makes data accessible and streamlines publishing, sharing, finding and using data - in this case, images and video.</p>

<p>The library has levels of security and access to ensure that data is used in the correct way depending on the licence and access level set by the owner of the data.</p>

<p>The library can store images and video, provide fast previews of video and it has the capability of aggregating creative commons data or social media content tagged with specific hashtags.&nbsp;</p>

<p>The library can securely connect data across the whole of government and, where applicable, to the public. The library can also provide a procurement and delivery platform for service providers who make images and video.</p>

<h2><strong>Images and videos are always protected</strong></h2>

<p>So, while the platform can grow and evolve and innovate, each collection will be managed by a registered user who will place the rights and permissions of the images and videos with the copyright holders and owners.</p>

<h2><strong>Streamlining Government</strong></h2>

<p>In the case of government assets, the system allows directorates to securely store, retrieve and share images and videos across all of government. Each individual image has protections, licence use and permissions and groups can individually manage their collections. The images can also be made publicly available.</p>

<h2><strong>Enabling local business and economic growth</strong></h2>

<p>Qualifying community groups, organisations business and individual users can also make use of the platform to share Canberra and region images.</p>

<p>The platform also has the capacity to develop a procurement channel for government or local business, buying images direct from suppliers. Additional capabilities planned for the future include the ability to monitor media by tracking hashtags such as images or tweets tagged with #CBR for instance. This capability allows expansion for the platform to accommodate the growing use of social media and to aggregate images to share through the city’s gateway website www.canberra.com.au</p>

<h2><strong>The future</strong></h2>

<p>This image library is just one project that can be built on a CBR Community Digital Platform. As the system is based on open source foundations, other digital data can be stored, shared and developed to serve the growing needs of a digitally connected and innovative city. If you are interested in how the platform can grow or want to get involved with an innovative project, contact us.</p>

<h1>CBR images</h1>

<p>The library’s look and feel reflects the whole of city branding<strong><span style="color:#FF0000">&nbsp; </span></strong>which is about growing the reputation of Canberra and our region and attracting more people to visit, study, live and do business here.</p>

<p>The selection of images reflects the brand values and personality, these key attributes being:</p>

<ul>
	<li>Genuine</li>
	<li>Influential</li>
	<li>Quality of Life</li>
	<li>Free Spirit</li>
	<li>Ideas</li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<h1><strong>Growing a brand through open data and the sharing economy</strong></h1>

<p>In what we believe is a world first, images and video of Canberra just got a whole lot easier to search, publish, share and use.</p>

<p>The library is available for images and video of the Canberra and the Canberra Region; how we live it, how we do business, what we make, our way of life and things that show what it means to live here.</p>

<p>A picture says a thousand words. As Brand Canberra works to support the growth in awareness and celebration of Australia’s capital city both domestically and abroad we have provided an innovative boost. The city now has an open data platform or library for finding and publishing images and video to promote the city and region.</p>

<p>The great thing about this image and video library is that is has been developed by Canberra innovators collaborating across business, research organisations and government. The model of this approach is gaining interest and uptake by governments across Australia and around the world to provide similar open data services.</p>

<h2><strong>Why a library?</strong></h2>

<h3>The digital storage dilemma</h3>

<p>How many of us in work and at home have hard drives, memory sticks, CDs and DVDs stored in cupboards, drawers and on desks. All disconnected, separated and not readily available. With the growth in digital data like images and videos, there is a global need to find more integrated, archival and accessible means to share valuable assets and resources.</p>

<h3>Whole of government efficiencies</h3>

<p>The ACT Government has long recognised the need for an ongoing integrated solution to data storage, acquisition, procurement, sharing and finding so as part of the Digital Challenge program a challenge was set to create a whole of government image and video library.</p>

<h3>Brand Canberra growth</h3>

<p>In addition to the internal efficiencies gained form a whole of government platform, images and video are the most valued and shared digital content across digital platforms, web and social media. There are images and videos shared to all manner of platforms every day. We recognised that for the CBR brand to grow we needed to provide a platform to share and trade images for all Canberrans who want to actively collaborate and contribute to promoting and celebrating Canberra and the region.</p>

<p>What began as a need for a whole of government image and video library grew into an exciting and innovative collaboration in turn creating the foundation of a CBR Community Data Platform.</p>

<h2><strong>How did the library happen?</strong></h2>

<p>Through the need for a more integrated whole of government approach to sourcing, storing, sharing and publishing images and in demand for better storage and access options, the requirements were defined and put forth as a Challenge opportunity through the Canberra Digital Challenge program.</p>

<p>The successful winner of that project round was LINK Digital who specialise in CKAN systems for open government data.</p>

<p>Opening data across government and to the public facilitates transparency, ease of sharing data across directorates, public participation and supports innovation by allowing third parties to use the data to develop new digital applications and services.</p>

<blockquote>
<p><em>Imagine being able to easily find an image of Canberra to help promote your city and region. Imagine being able to share or sell images to celebrate what you love, support your local businesses and work collaboratively to grow awareness, pride and recognition of CBR. You’ve just seen the value of the CBR open sourced image and video library. </em></p>
</blockquote>

<h2><strong>Who’s behind the library?</strong></h2>

<p>Brand Canberra along with Data 61 and LINK Digital has developed the data portal for images and videos. This platform gives everyone the opportunity to create and share their own Canberra story.</p>

<h2><strong>What makes this an open source library?</strong></h2>

<p>The exciting potential for the library is that it can connect individuals, business, government and organisations to share, transact and grow a common resource and asset to serve the good of the whole in promoting and celebrating our great city.</p>

<p>Using the power of cloud-based, powerful data management system called CKAN, the ACT Government in collaboration with Canberra business LINK Digital, NICTA and Brand Canberra is providing the platform to streamline publishing, sharing, finding and using data.</p>

<p>Being open source means that the structure of the platform can grow, be improved, adapted and integrated into a host of digital platforms and apps by developers so to future-proof the capability.</p>

<h2><strong>Who is the library for?</strong></h2>

<p>The ACT Government is committed to more transparent and accessible ways of engaging and reporting to the public and this platform is a great example of working with government, business and research organisations to collaborate on innovative outcomes.</p>

<p>The library is an open data platform. It is a place to store, exchange, transact and share images and video of Canberra and the Canberra Region. Initially built for the ACT Government for internal use, the library structure offers the space and potential for community groups, businesses and individuals to use as a shared resource.</p>

<p>Qualifying owners of a collection (data set) create an account that permits them to upload, store, catalogue, sort, retrieve, share and distribute images and video.</p>

<h3>Collection owners</h3>

<p>The owner of a collection (data set) adds their images and video, includes keywords for searching and metadata about their collection and determines the levels of access, viewing, licensing and permissions for other users. For instance, a departmental user may allow only authorised staff within that department to have access, or may make the data set open to all users.</p>

<h3>Collection users</h3>

<p>End users can also create an account and browse and download images and video depending on the licence for each image or video. Any transactions that require permissions or payment are done within the platform.</p>

<h3>Image and video suppliers</h3>

<p>Suppliers of images and video can create an account and add deliver their images to their client’s collection, adding metadata and keywords as specified in their brief. The collection is then managed by the client according to their set level of access and permissions.</p>

<h3>Business users</h3>

<p>Businesses can register to make use of freely available images to promote Canberra and the region and in time they too can also purchase images for sale through the platform, effectively providing a potential future market place to link suppliers of images and videos with suppliers. This potential is similar to a conventional stock library, but the content is specific to Canberra and the region.</p>

<h3>General public, community, sporting groups and organisations</h3>

<p>The public can also register to be a user of images and download images for fair use based on the licence set by the owner. With suitable registration and permission, the platform can also be configured to aggregate social media content around known, specified hashtags. This means the potential to collect social media content around an event, festival or activity can be arranged so the organisers can easily aggregate and share content around their event, or have it featured on the Canberra.com.au website. The platform is primarily used for the #CBR hashtag, but other hashtags can be considered.&nbsp;</p>

<p>Finally the library can provide a platform where groups including individuals, community organisations, sporting clubs, universities and business can store, share and sell images to support the healthy depiction and promotion of the Canberra Region.</p>

<h2><strong>What can the library do?</strong></h2>

<p>The library is built on a powerful open source data portal platform called CKAN. The library makes data accessible and streamlines publishing, sharing, finding and using data - in this case, images and video.</p>

<p>The library has levels of security and access to ensure that data is used in the correct way depending on the licence and access level set by the owner of the data.</p>

<p>The library can store images and video, provide fast previews of video and it has the capability of aggregating creative commons data or social media content tagged with specific hashtags.&nbsp;</p>

<p>The library can securely connect data across the whole of government and, where applicable, to the public. The library can also provide a procurement and delivery platform for service providers who make images and video.</p>

<h2><strong>Images and videos are always protected</strong></h2>

<p>So, while the platform can grow and evolve and innovate, each collection will be managed by a registered user who will place the rights and permissions of the images and videos with the copyright holders and owners.</p>

<h2><strong>Streamlining Government</strong></h2>

<p>In the case of government assets, the system allows directorates to securely store, retrieve and share images and videos across all of government. Each individual image has protections, licence use and permissions and groups can individually manage their collections. The images can also be made publicly available.</p>

<h2><strong>Enabling local business and economic growth</strong></h2>

<p>Qualifying community groups, organisations business and individual users can also make use of the platform to share Canberra and region images.</p>

<p>The platform also has the capacity to develop a procurement channel for government or local business, buying images direct from suppliers. Additional capabilities planned for the future include the ability to monitor media by tracking hashtags such as images or tweets tagged with #CBR for instance. This capability allows expansion for the platform to accommodate the growing use of social media and to aggregate images to share through the city’s gateway website www.canberra.com.au</p>

<h2><strong>The future</strong></h2>

<p>This image library is just one project that can be built on a CBR Community Digital Platform. As the system is based on open source foundations, other digital data can be stored, shared and developed to serve the growing needs of a digitally connected and innovative city. If you are interested in how the platform can grow or want to get involved with an innovative project, contact us.</p>

<h1>CBR images</h1>

<p>The library’s look and feel reflects the whole of city branding<strong><span style="color:#FF0000">&nbsp; </span></strong>which is about growing the reputation of Canberra and our region and attracting more people to visit, study, live and do business here.</p>

<p>The selection of images reflects the brand values and personality, these key attributes being:</p>

<ul>
	<li>Genuine</li>
	<li>Influential</li>
	<li>Quality of Life</li>
	<li>Free Spirit</li>
	<li>Ideas</li>
</ul>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:5:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2015-04-01 09:54:40 +0000',
);
  return $nodes;
}
